### ISSUE TITLE
katana --update still references master branch instead of main

### ISSUE THREAD

**Issue by tracure1337** [SamuraiWTF/katana#56]
```
samurai@SamuraiWTF:/opt/katana$ katana --update
Updating Katana...
/tmp /opt/katana
Cloning repository branch 'master'
Cloning into 'katana'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
samurai@SamuraiWTF:/opt/katana$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
samurai@SamuraiWTF:/opt/katana$ git remote -v
origin	https://github.com/SamuraiWTF/katana (fetch)
origin	https://github.com/SamuraiWTF/katana (push)
```

**Comment by secureideas** [comment]
May I ask when you installed samurai and katana?

Can you try katana --update main   ?

Thanks

**Comment by JGillam** [comment]
This looks like it was from an older version of SamuraiWTF (before we switched the katana branch to main).  We are currently working out a new VM image but that will likely take a few days.  If you need this to work in the short term, you can try

### Option 1
 `katana --update main`

### Option 2
You can manually patch the script that does the update.  That script is defined in the [ansible playbook in the main SamuraiWTF project](https://github.com/SamuraiWTF/samuraiwtf/blob/cf4d3f1b4c172e23db22412b8ab293194f35b0ae/amazon-linux/local_playbook.yml#L283)

If this is not urgent, we should have a new VM image available soon and for this one we are planning to get one that builds for hyperv and virtualbox.  This also means it may be a different Linux distro since the box we used for Amazon Linux doesn't build for hyperv natively (we are looking at CentoOS, Fedora, and Ubuntu base boxes at the moment).

**Comment by tracure1337** [comment]
Appreciate the swift reply.

This is not urgent at all and thank your for the suggested short-term fixes.

I  am using the version provided via https://github.com/SamuraiWTF/samuraiwtf and the prebuilt OVA.

Will check now and download the most recent version, that will probably fix it and I just did not realize at all that a new OVA was released. 

Will report back asap.

**Comment by tracure1337** [comment]
Yes indeed it's amazon linux now. I exported to a OVA for my vmware workstation and it works but I cannot install the vmware tools.

I will use the  older version with the manual fixes for now.

Thanks again for taking the time!

**Comment by tracure1337** [comment]
Was able to install them with 
```yum install open-vmware-tools```

works like a charm!
